<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="LinkVentaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="pruebapizza2.Properties.Settings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Venta" Member="Venta">
    <Type Name="Venta">
      <Column Name="fecha" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCajero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>